# Generated by Django 3.2.6 on 2021-08-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='NameTour',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Content',
            new_name='TypeTour',
        ),
    ]
