# Generated by Django 3.2.6 on 2021-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CreationDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
