# Generated by Django 3.2.6 on 2021-08-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0005_post_creationdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-CreationDate']},
        ),
    ]
